config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  # resources :stocks
  devise_for :users
  # get 'home/index'
  root "home#index"
  get "home/about"

  post "/" => "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  validates :ticker, presence: true
  validates :ticker, format: { without: /\s/, message: "must not contain spaces" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require "open-uri"
require "json"
# Full API Stock
# https://financialmodelingprep.com/api/v3/search?query=AA&apikey=TjBA95mM5eWMsdlGrByYgll9ye0IifR8
class HomeController < ApplicationController
  # https://financialAAPLmodelingprep.com/api/v3/quote/AAPL?apikey=TjBA95mM5eWMsdlGrByYgll9ye0IifR8
  def index
    @api_key = "TjBA95mM5eWMsdlGrByYgll9ye0IifR8"
    @ticker = params[:ticker]

    if @ticker.blank?
      @nothing = "Hey! You Forgot To Enter A Symbol"
    else
      begin
        # https://financialmodelingprep.com/api/v3/quote/AAPL?apikey=TjBA95mM5eWMsdlGrByYgll9ye0IifR8
        # Fetch stock data
        # @url = "https://financialmodelingprep.com/api/v3/quote/#{@ticker}?apikey=#{@api_key}"
        # @uri = URI(@url)
        # response = Net::HTTP.get(@uri)
        url = "https://financialmodelingprep.com/api/v3/quote/#{@ticker}?apikey=#{@api_key}"
        response = URI.open(url).read
        @stock = JSON.parse(response).first # Parse JSON and take the first element (because the response is an array)

        if @stock.nil?
          @error = "Hey! That Stock Symbol Doesn't Exist. Please Try Again."
        end
      rescue => e
        @error = "Error fetching stock data: #{e.message}"
      end
    end
  end

  def about
  end
end


=begin
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_16a849fd637243a79fff90fa4d42bc5d')

    if params[:ticker] == ""
      @nothing = "Hey! You Forgot To Enter A Symbol"
    elsif params[:ticker]
      @stock = StockQuote::Stock.quote(params[:ticker])
      if !@stock
        @error = "Hey! That Stock Symbol Doesn't Exist. Please Try Again."
      end

    end

  end

  def about
  end

end
=end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  # before_action :set_stock, only: [ :show, :edit, :update, :destroy ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)
    # Check if the user exists
    @user = User.find_by(id: @stock.user_id)
    if @user.nil?
      flash[:error] = "User must exist"
      render :new and return
    end


    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        # Log validation errors
        Rails.logger.error @stock.errors.full_messages.join(", XXX ")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy!

    respond_to do |format|
      format.html { redirect_to stocks_path, status: :see_other, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not authorized to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.expect(stock: [ :ticker, :user_id ])
    end
end


=begin
require "open-uri"

class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  # before_action :set_stock, only: [ :show, :edit, :update, :destroy ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @api_key = "TjBA95mM5eWMsdlGrByYgll9ye0IifR8"
    api_url = "https://financialmodelingprep.com/api/v3/stock/list?apikey=#{@api_key}"

    # Open the URL and parse the JSON response
    response = URI.open(api_url).read
    @stocks_data = JSON.parse(response).take(100)  # Limit to first 100 stocks
  end


  # GET /stocks/1 or /stocks/1.json
  def show
    @ticker = params[:ticker]
    @api_key = "TjBA95mM5eWMsdlGrByYgll9ye0IifR8"
    api_url = "https://financialmodelingprep.com/api/v3/quote/#{@ticker}?apikey=#{@api_key}"

    # Open the URL and parse the JSON response
    response = URI.open(api_url).read
    @stock_data = JSON.parse(response).first # Get the first result from the API response
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find_by(symbol: params[:symbol])
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)
    @user = User.find_by(id: @stock.user_id)
    if @user.nil?
      flash[:error] = "User must exist"
      render :new and return
    end

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        Rails.logger.error @stock.errors.full_messages.join(", ")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy!

    respond_to do |format|
      format.html { redirect_to stocks_path, status: :see_other, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_stock
      @stock = Stock.find(params[:id])  # Corrected the typo
    end

    def stock_params
      params.require(:stock).permit(:ticker, :user_id)  # Fixed strong parameters
    end
end


=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
		<div class="alert alert-success alert-dismissable" role="alert">
			<button class="close" data-dismiss="alert">
				<small><sup>x</sup></small>
			</button>
			<%= content_tag(:div, msg) %>
		</div>
<% end %>

app/views/home/_footer.html.erb
<center >
  <footer class="blockquote-footer">Copyrigth (c) <cite title="Source Title">Meow Merry: https://github.com/Meowmerry</cite></footer>
</center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Stocking", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      	<%= link_to "About", home_about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Add Stock", new_stock_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger ml-3" %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Me!</h1>
<p>Hello! My name is Meow Merry!</p>

app/views/home/index.html.erb
<h1>Stocking</h1>

<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
	<%= submit_tag 'Lookup' %>
<% end %>


<br/>

<% if @stock %>
	<%# <%= @stock.inspect %>
  <%= @stock['name'] %><br/>
	$<%= @stock['price'] %><br/>
  <%= @stock['changesPercentage'] %><br/>
<% elsif @nothing %>
	<%= @nothing %>
<% end %>
 
<% if @error %>
	<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Stock Market App With Ruby On Rails" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "bootstraply", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="wrapper">
      <%= render "home/navbar" %>
      <div class="container mt-4">
         <%= render 'home/flash', class:'mb-2'%>
        <%= yield %>
        <%# yield will take all code in other file to be wrapped in application.html.erb %>
      </div>
    </div>
    <%= render "home/footer" %>

    <%# Add the required Bootstrap and jQuery scripts %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/stocks/_fake_index.html.erb
<!--


<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <%# <% logger.debug "Stocks Data: #{@stocks_data.inspect}" %> 

    <% @stocks_data.each do |stock| %>
      <tr>
        <% if stock["symbol"].nil? %>
          <td><%= link_to "Error", '#' %></td>
          <td><%= stock["symbol"] %></td>
          <td>N/A</td>
          <td>N/A</td>
          
           <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        <% else %>
          <td><%= link_to stock["name"], "#" %></td>
          <td><%= stock["symbol"] %></td>
          <td>$<%= number_with_precision(stock["price"].to_f, precision: 2, delimiter: ',') %></td>
          <td><%= stock["exchange"] %></td>
           <td><center><%= link_to 'Edit' %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

-->

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, id: :stock_ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :stock_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions mt-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Ticker:</strong>
    <%= stock.ticker %>
  </p>

  <p>
    <strong>User:</strong>
    <%= stock.user_id %>
  </p>

</div>

app/views/stocks/edit.html.erb
<% content_for :title, "Editing stock" %>

<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<!-- Stock Table -->
<h3>Your Stocks</h3>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
        <!-- Assuming @ticker contains stock details -->
        <% if !@ticker %>
          <tr>
            <td><%= link_to stock.name, stock.ticker %></td>
            <td><%= stock.ticker %></td>
            <td>N/A</td>
            <td>N/A</td>
            <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
            <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to @ticker.company_name, stock %></td>
            <td><%= @ticker.symbol %></td>
            <td>$<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %></td>
            <td>$<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %></td>
            <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
            <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Stock', new_stock_path, class: 'mb-3 p-3' %>

app/views/stocks/new.html.erb
<% content_for :title, "New stock" %>

<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<% @api = StockQuote::Stock.new(api_key: 'pk_16a849fd637243a79fff90fa4d42bc5d') %>

<% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
      <% if !@ticker %>
        
         The ticker: <%= @stock.ticker %><br/> does not exist!
          
          
          
      <% else %>
        <% @logo = StockQuote::Stock.logo(@stock.ticker)%>
        <img src="<%= @logo.url %>"><br/><br/>

          <h2><%= @ticker.company_name %></h2><br/>
          Ticker Symbol: <%= @ticker.symbol %><br/>
          Current Price: $<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %><br/>

          Previous Close: $<%= number_with_precision(@ticker.previous_close, :precision => 2, :delimiter => ',') %><br/>

          Percent Change: <%= @ticker.change_percent %>%<br/>

          YTD Change: <%= number_with_precision(@ticker.ytd_change, :precision => 2, :delimiter => ',') %>%<br/>
	                    
          Market Cap: $<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %><br/>

          <!-- remove sector reference for stock_quote 3.0 gem -->


          
      
      <% end %>


<br/><br/>
<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>